accounts/urls.py
from django.urls import path,include
from . import views
from . views import *
from django.contrib.auth.views import LoginView
from django.contrib.auth.views import LogoutView

app_name= 'accounts'

urlpatterns = [
   path('new-user', UserRegistrationView.as_view(), name='user_registration'),
   path('login', LoginView.as_view(template_name='products/login.html'), name="login"),
   path('logout', LogoutView.as_view(template_name='products/login.html'), name="logout"),
   path('products',include('products.urls')),
]

onlinebookstore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls')),
    path('', include('accounts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('',views.store, name="store"),
    path('cart/', views.cart, name = "cart"),
    path('checkout/', views.checkout, name = "checkout"),
    path('update_item/', views.updateItem, name = "update_item"),
    path('process_order/', views.processOrder, name = "process_order"),
    
]

accounts/models.py
from django.db import models

# Create your models here.

products/models.py
from django.db import models
from django.contrib.auth.models import User

class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200, null=True)
    email = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.name
    
class Product(models.Model):
    name = models.CharField(max_length=200, null=True)
    price = models.DecimalField(max_digits=7,decimal_places=2)
    digital = models.BooleanField(default=False, null=True, blank=False)
    image = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.name

    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url
    
    _metadata = {
        'title':'name',
        'images': 'get_meta_image',
        }

    def get_meta_image(self):
        if self.image:
            return self.image.url


class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, blank=True, null=True)
    date_ordered = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False, null=True, blank=False)
    transaction_id = models.CharField(max_length=200, null=True)

    def __str__(self):
        return str(self.id)
    
    @property
    def shipping(self):
        shipping = False
        orderitems = self.orderitem_set.all()
        for i in orderitems:
            if i.product.digital == False:
                shipping = True
        return shipping
    
    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total

    @property
    def get_cart_items(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitems])
        return total

class OrderItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
    quantity = models.IntegerField(default=0, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    @property
    def get_total(self):
        total = self.product.price * self.quantity
        return total

class ShippingAddress(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, blank=True, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, blank=True, null=True)
    address = models.CharField(max_length=200, null=True)
    city = models.CharField(max_length=200, null=True)
    state = models.CharField(max_length=200, null=True)
    zipcode = models.CharField(max_length=200, null=True)    
    date_added = models.DateTimeField(auto_now_add=True)    

    def __str__(self):
        return self.address

accounts/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse
from django.views.generic import CreateView
from products.views import *



class UserRegistrationView(CreateView):
    form_class = UserCreationForm
    template_name = 'products/user_registration.html'

    def get_success_url(self):
        return reverse('store')
    

products/views.py
from django.shortcuts import render
from django.http import JsonResponse
import datetime
import json
from .models import  *
from .utils import *


def store(request):
    data  = cartData(request)
    cartItems = data['cartItems']

    products = Product.objects.all()
    context = {"products":products, 'cartItems':cartItems}
    return render(request, 'products/store.html', context)


def cart(request):
    data  = cartData(request)
    cartItems = data['cartItems']
    order = data['order']
    items = data['items']

    context = {'items':items, 'order':order, 'cartItems':cartItems}
    return render(request, 'products/cart.html', context)


def checkout(request):
    data  = cartData(request)
    cartItems = data['cartItems']
    order = data['order']
    items = data['items']

    context = {'items':items, 'order':order, 'cartItems':cartItems, 'shipping':False}
    return render(request, 'products/checkout.html', context)


def updateItem(request):
    data = json.loads(request.body)
    productId = data['productId']
    action = data['action']
    print('Action :', action)
    print('productId :',productId)
    customer = request.user.customer
    product = Product.objects.get(id=productId)
    # below line attaches the order to the given customer
    order, created = Order.objects.get_or_create(customer=customer, complete=False)
   
    orderItem, created = OrderItem.objects.get_or_create(order=order, product=product)

    if action =='add':
        # by clicking up arrow, increment orderItem by 1
        orderItem.quantity = (orderItem.quantity + 1)
    elif action == 'remove':
        # by clicking up arrow, decrement orderItem by 1
        orderItem.quantity = (orderItem.quantity - 1)

    # save quantity of products, for an order
    orderItem.save()

    if orderItem.quantity <= 0:
        # remove the orderItem from cart, when quantity reaches 0, or below it
        orderItem.delete()

    return JsonResponse('Item was added', safe=False)


def processOrder(request):
    transaction_id = datetime.datetime.now().timestamp()
    data = json.loads(request.body)

    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, complete=False)

    else:
        # guestOrder function is present in utils.py
        customer, order = guestOrder(request, data)

    total = float(data['form']['total'])
    order.transaction_id = transaction_id

    if total == order.get_cart_total:
        order.complete = True
    order.save()

    if order.shipping == True:
        ShippingAddress.objects.create(
            customer = customer,
            order = order,
            address = data['shipping']['address'],
            city = data['shipping']['city'],
            state = data['shipping']['state'],
            zipcode = data['shipping']['zipcode'],
            )

    return JsonResponse("Payment submitted...",safe=False)

products/templates/products/cart.html
{% extends 'products/main.html' %}
{% load static %}
{% block content %}

<div class="row">
    <div class="col-lg-12">
        <div class="box-element">
            <a class="btn btn-outline-dark" href="{% url 'store' %}">&#x2190; Continue Shopping</a>

            <br>
            <br>

            <table class="table">
                <tr>
                <th><h5>Items: <strong>{{order.get_cart_items}}</strong></h5></th>
                    <th><h5>Total: <strong>{{order.get_cart_total|floatformat:2}}</strong></h5></th>
                    <th>
                        <a style="float:right; margin: 5px;" class="btn btn-success"
                         href="{% url 'checkout' %}">Checkout</a>
                    </th>
                </tr>
            </table>
        </div>

        <div class="box-element">
            <div class="cart-row">
                <div style="flex:2"></div>
                <div style="flex:2"><strong>Item</strong></div>
                <div style="flex:1"><strong>Price</strong></div>
                <div style="flex:1"><strong>Quantity</strong></div>
                <div style="flex:1"><strong>Total</strong></div>
            </div>

            {% for item in items %}
            <div class="cart-row">
                <div style="flex:2"><img class="row-image" src="{{item.product.imageURL}}"></div>
                <div style="flex:2">{{item.product.name}}</div>
                <div style="flex:1">Rs {{item.product.price|floatformat:2}}</div>
                <div style="flex:1">
                    <p class="quantity">{{item.quantity}}</p>
                    <div class="quantity">
                        <img data-product={{item.product.id}} data-action="add" class="chg-quantity update-cart" src="{% static 'images/arrow-up.png' %}">

                        <img data-product={{item.product.id}} data-action="remove" class="chg-quantity update-cart" src="{% static 'images/arrow-down.jpg' %}">
                    </div>
                </div>
                <div style="flex:1">Rs {{item.get_total}}</div>
            </div>
            {% endfor %}
        </div>        

    </div>
</div>

{% endblock content %}

products/templates/products/checkout.html
{% extends 'products/main.html' %}
{% load static %}
{% block content %}
     <div class="row">
		<div class="col-lg-6">
			<div class="box-element" id="form-wrapper">
				<form id="form" method="post">
          {% csrf_token %}
					<div id="user-info">
						<div class="form-field">
							<input required class="form-control" type="text" name="name" placeholder="Name..">
						</div>
						<div class="form-field">
							<input required class="form-control" type="email" name="email" placeholder="Email..">
						</div>
					</div>

					<div id="shipping-info">
						<hr>
						<p>Shipping Information:</p>
						<hr>
						<div class="form-field">
							<input class="form-control" type="text" name="address" placeholder="Address..">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="city" placeholder="City..">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="state" placeholder="State..">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="zipcode" placeholder="Zip code..">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="country" placeholder="Country..">
						</div>
					</div>

					<hr>
					<input id="form-button" class="btn btn-success btn-block" type="submit" value="Continue">
				</form>
			</div>

			<br>
			<div class="box-element hidden" id="payment-info">
				<p>Payment Options :</p>
        <div id="paypal-button-container"></div>
        <!--button id="make-payment">Make Payment</button-->
			</div>

		</div>

		<div class="col-lg-6">
			<div class="box-element">
				<a  class="btn btn-outline-dark" href="{% url 'cart' %}">&#x2190; Back to Cart</a>
				<hr>
				<h3>Order Summary</h3>
				<hr>
        {% for item in items %}
				<div class="cart-row">
					<div style="flex:2"><img class="row-image" src="{{ item.product.imageURL }}"></div>
					<div style="flex:2"><p>{{ item.product.name }}</p></div>
					<div style="flex:1"><p>Rs. {{ item.product.price|floatformat:2 }}</p></div>
					<div style="flex:1"><p>{{ item.quantity }}</p></div>
				</div>
        {% endfor %}
				<h5>Items:   {{ order.get_cart_items }}</h5>
				<h5>Total:  Rs. {{ order.get_cart_total|floatformat:2 }}</h5>
			</div>
		</div>
</div>

  <script src="https://www.paypal.com/sdk/js?client-id=ASIvsqBOwc87K9czz_rkh0aoyw3bdINpnNQh_A0DbfCOutwY8l4Q_eaYPiIPluPUEPN9nRGcc1oAJFyD&currency=USD"></script>

  <script>
    var total = '{{order.get_cart_total}}'
        // Render the PayPal button into #paypal-button-container
        paypal.Buttons({

          style:{
            color: 'blue',
            shape: 'pill',
            size: 'responsive',
            label: 'paypal',
          },
            // Set up the transaction
            createOrder: function(data, actions) {
                return actions.order.create({
                    purchase_units: [{
                        amount: {
                            value: 50
                        }
                    }]
                });
            },

            // Finalize the transaction
            onApprove: function(data, actions) {
                return actions.order.capture().then(function(details) {
                    submitFormData()
                });
            }


        }).render('#paypal-button-container');
    </script>


  <script type="text/javascript">
      var shipping = '{{order.shipping}}'


      if (shipping == "False"){
        document.getElementById('shipping-info').innerHTML = ''
      }

      if (user != 'AnonymousUser') {
          document.getElementById('user-info').innerHTML = ''
      }

      if (shipping == 'False' && user != 'AnonymousUser') {
        //Hide entire form if user is logged in and shipping is false
        document.getElementById('form-wrapper').classList.add("hidden");
        //Show payment, if logged in user wants to buy an item, tht doesn't require shipping
        document.getElementById('payment-info').classList.remove("hidden");
      }

      var form = document.getElementById('form')

      // the below code takes the csrftoken generated by the form in incognito mode,
      // and passes it to the backend for processing of payment
      csrftoken = form.getElementsByTagName('input')[0].value
      console.log('NewToken:', form.getElementsByTagName('input')[0].value)

      //the below event triggers, on clicking the submit button
      form.addEventListener('submit',function(e){
        e.preventDefault()
        console.log('Form Submitted...')
        document.getElementById('form-button').classList.add('hidden');
        document.getElementById('payment-info').classList.remove('hidden');
      })

      /*
      document.getElementById('make-payment').addEventListener('click',function(e){

      })
      */

      function submitFormData(){
        console.log('Payment button clicked')

        var userFormData ={
          'name':null,
          'email':null,
          'total':total
        }

        var shippingInfo ={
          'address':null,
          'city':null,
          'state':null,
          'zipcode':null,
        }

        if (shipping != 'False') {
            shippingInfo.address = form.address.value
            shippingInfo.city = form.city.value
            shippingInfo.state = form.state.value
            shippingInfo.zipcode = form.zipcode.value
        }

        if (user == 'AnonymousUser') {
            userFormData.name = form.name.value
            userFormData.email = form.email.value
        }

        var url = '/process_order/'
        fetch(url, {
          method : 'POST',
          headers : {
            'Content-Type' : 'application/json',
            'X-CSRFToken' : csrftoken,
          },
          body : JSON.stringify({'form':userFormData, 'shipping':shippingInfo})
        })
        .then((response) => response.json())
        .then((data) => {
          console.log('Success:',data);
          alert('Transaction Completed');

          // the below line, clears out our cookies, after checkout has been completed
          // and, later we are redirected to the home page, along with an empty cart
          cart = {}
          document.cookie = 'cart=' + JSON.stringify(cart) + ";domain=;path=/"

          window.location.href = "{% url 'store' %}"
        })

      }
  </script>
{% endblock content %}

products/templates/products/login.html
{% extends "products/main.html" %}
{% load static %}
{% block content %}
<h1>Login</h1>
<form action="{% url 'accounts:login' %}" method="post">{% csrf_token %}
    {{ form.as_p }}

    <input type="hidden" name="next" value="{{ next }}" />
    <input type="submit" value="Submit" />
</form>
{% endblock %}

products/templates/products/main.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head >

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Online Book Store</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'css/main.css' %}">

    <script type="text/javascript">
        var user = '{{request.user}}'
            function getToken(name) {
                    var cookieValue = null;
                    if (document.cookie && document.cookie !== '') {
                            var cookies = document.cookie.split(';');
                            for (var i = 0; i < cookies.length; i++) {
                                    var cookie = cookies[i].trim();
                                    // Does this cookie string begin with the name we want?
                                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                                            cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                                            break;
                                    }
                            }
                    }
                    return cookieValue;
            }
            var csrftoken = getToken('csrftoken')

            function getCookie(name) {
                // Split cookie string and get all individual name=value pairs in an array
                var cookieArr = document.cookie.split(";");

                // Loop through the array elements
                for(var i = 0; i < cookieArr.length; i++) {
                    var cookiePair = cookieArr[i].split("=");

                    /* Removing whitespace at the beginning of the cookie name
                    and compare it with the given string */
                    if(name == cookiePair[0].trim()) {
                        // Decode the cookie value and return
                        return decodeURIComponent(cookiePair[1]);
                    }
                }

                // Return null if not found
                return null;
            }
        var cart = JSON.parse(getCookie('cart'))

        if(cart == undefined){
            cart = {}
            console.log('Cart Created!')
            document.cookie ='cart=' + JSON.stringify(cart) + ";domain=;path=/"
        }
        console.log('Cart:', cart)
    </script>

</head>
<body>
    
    <nav class="navbar navbar-expand-lg bg-body-tertiary bg-dark border-bottom border-bottom-dark" data-bs-theme="dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'store' %}">BookSagar</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'store' %}">Store</a>
                </li>
                </ul>

                <div class="form-inline my-2 my-lg-0">
                    {% if request.user.is_authenticated %}
                    <a href="{% url 'accounts:logout' %}" class="btn btn-warning">Logout</a>
                    {% else %}
                    <a href="{% url 'accounts:login' %}" class="btn btn-warning">Login</a>
                    <a href="{% url 'accounts:user_registration' %}" class="btn btn-warning">Register</a>
                    {% endif %}
                    
                    <a href="{% url 'cart' %}">
                        <img src="{% static 'images/cart.jpg' %}" id="cart-icon">
                    </a>
                    <p id="cart-total">{{cartItems}}</p>
                </div>


            </div>
        </div>
    </nav>

    <div class="container">
        {% block content %}

        {% endblock content %}
    </div>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js" integrity="sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS" crossorigin="anonymous"></script>

    <script type="text/javascript" src="{% static 'js/cart.js' %}"></script>

</body>
</html>

products/templates/products/store.html
{% extends 'products/main.html' %}
{% load static %}
{% block content %}

    <div class="row">
        {% for product in products %}
        <div class="col-lg-4">
            <img class="thumbnail" src="{{ product.imageURL }}">
            <div class="box-element product">
                <h6><strong>{{product.name}}</strong></h6>
                <hr>
                <button data-product={{product.id}} data-action="add" class="btn btn-outline-secondary add-btn update-cart">Add to Cart</button>
                <a class ="btn btn-outline-success" href="#">View</a>
                <h5 style="display: block; float: right">
                    Rs {{product.price|floatformat:2}}</h5>
            </div>
        </div>
        {% endfor %}
    </div>

{% endblock content %}

products/templates/products/user_registration.html
{% extends "products/main.html" %}
{% load static %}
{% block content %}
<h1>Create Account</h1>
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Create Account" />
</form>
{% endblock %}